In [1]:
import  numpy as np

In [1]:
import jovian

In [2]:
nx, ny = (3, 2)
print(nx)
print(ny)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)

3
2


In [2]:
jovian.commit(filename="assignment")

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.com/stephenmandivinga/assignment


'https://jovian.com/stephenmandivinga/assignment'

In [3]:
print(x)
print(y)

[0.  0.5 1. ]
[0. 1.]


In [4]:
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


In [6]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 10, endpoint=False)

X, Y = np.meshgrid(x, y)

print(X)
print(Y)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.  0.  0.  0.  0. ]
 [0.1 0.1 0.1 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3 0.3]
 [0.4 0.4 0.4 0.4 0.4]
 [0.5 0.5 0.5 0.5 0.5]
 [0.6 0.6 0.6 0.6 0.6]
 [0.7 0.7 0.7 0.7 0.7]
 [0.8 0.8 0.8 0.8 0.8]
 [0.9 0.9 0.9 0.9 0.9]]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.  0.  0.  0.  0. ]
 [0.1 0.1 0.1 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3 0.3]
 [0.4 0.4 0.4 0.4 0.4]
 [0.5 0.5 0.5 0.5 0.5]
 [0.6 0.6 0.6 0.6 0.6]
 [0.7 0.7 0.7 0.7 0.7]
 [0.8 0.8 0.8 0.8 0.8]


In [8]:
import numpy as np

# Case 1: non-one-dimensional input arrays
x = np.array([[[1, 2, 3], [4, 5, 6]]])
y = np.array([7, 8, 9])
try:
    X, Y = np.meshgrid(x, y)
except ValueError as e:
    print(e)  # "Input arrays must be 1D"

# Case 2: too many input dimensions
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
try:
    X, Y, Z = np.meshgrid(x, y, z, indexing='ij')
except ValueError as e:
    print(e)  # "Too many input dimensions"

In [18]:
output = np.arange(1,101).reshape(5, 2,10)

In [17]:
print(output.shape)

(5, 2, 10)


In [24]:
x,y = np.meshgrid(output,y)

In [25]:
print(y)

[[ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1  1]
 ...
 [17 17 17 ... 17 17 17]
 [17 17 17 ... 17 17 17]
 [17 17 17 ... 17 17 17]]


In [26]:
arr1 = np.array([1, 2, 3])
arr2 = 4

result = np.intersect1d(arr1, arr2)

print(result)

[]


In [27]:
arr = np.array([1, 2, 3])

result = np.tile(arr, 2.5)

print(result)

TypeError: 'float' object cannot be interpreted as an integer

In [29]:
arr = np.array([1, 2, 3])

result = np.transpose(output, (1, 0))

print(result)

ValueError: axes don't match array

In [30]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8])

result = np.stack((arr1, arr2, arr3))

print(result)

ValueError: all input arrays must have the same shape

In [31]:
import numpy as np

x = np.array([1.2, 2.4, 3.6, 4.8, 6.0])
bins = np.array([6.0, 4.0, 2.0, 0.0])

result = np.digitize(x, bins)

print(result)

[3 2 2 1 0]


In [32]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.einsum('i,j', a, b)

print(result)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [33]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

result = np.var(a, axis=1)

print(result)

AxisError: axis 1 is out of bounds for array of dimension 1