In [4]:
import numpy as np

arr3 = np.array([
    [[11, 12, 8, 19],
     [13, 21, 4, 19]],

    [[5, 1, 7, 21],
     [13, 9, 6, 1]],

    [[9, 32, 18, -5],
     [15, 25, 11, -6]]])
print(arr3[:2, 1])

[[13 21  4 19]
 [13  9  6  1]]


In [20]:
arr1 = np.array([7, 8])
arr2= np.array([[1],[2]])
arr1*arr2

array([[ 7,  8],
       [14, 16]])

In [21]:
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])
arr2 = np.array([[[1, 2, 3, 4]],
                 [[5, 6, 7, 8]],
                 [[9, 1, 2, 3]]])
arr1+arr2

array([[[ 2,  4,  6,  8],
        [ 6,  8, 10, 12],
        [10,  3,  5,  7]],

       [[ 6,  8, 10, 12],
        [10, 12, 14, 16],
        [14,  7,  9, 11]],

       [[10,  3,  5,  7],
        [14,  7,  9, 11],
        [18,  2,  4,  6]]])

In [19]:
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])
arr2 = np.array([7, 8])
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [18]:
arr1 = np.array([7, 8, 9])
arr2 = np.array([[1,2],[2,3],[7,5]])
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [7]:
a = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]
b = [[1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1]]

print(np.concatenate([a,b],axis=1))
print(np.hstack([a,b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [23]:
trt = (23,45,67,100,44)
trt[1:]

(45, 67, 100, 44)

In [13]:
arrr = [[1, 2], [2, 3], [3., 4, 5]]

In [14]:
print(np.array(arrr).dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [15]:
a=np.array([[1,2],[4,5]])

b=np.array([[7,8],[9,10]])

In [16]:
np.dot(a,b)

array([[25, 28],
       [73, 82]])

In [17]:
aa = np.arange(10)
ab = np.arange(10)
print(np.dot(aa,ab))

285
